### Get user Info
GET https://do-an-da-nganh.onrender.com/api/users/info/vinhnguyenkhac20@gmail.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aW5obmd1eWVua2hhYzIwQGdtYWlsLmNvbSIsImV4cCI6MTczMDkyMDg5OX0.KB4wCuIbWXzZRCnf1DZCMlM3f1sLvg49lnPN3AKBNWQ


### Update information users
POST https://do-an-da-nganh.onrender.com/api/users/signup
Content-Type: application/json

{
    "IP": "09034",
    "first_name": "Nguyen Khac",
    "last_name": "Vinh",
    "username": "adamnguyen",
    "password": "123456789",
    "email": "vinhnguyenkhac20@gmail.com",
    "phoneNumber": "0345621376",
    "address": "Road N, Block K",
    "role": "user"
}


### Đăng Nhập
POST https://do-an-da-nganh.onrender.com/api/users/signin
Content-Type: application/json

{
    "email": "034",
    "password": "123456"
}


### Đăng Nhập
POST https://do-an-da-nganh.onrender.com/api/users/signin
Content-Type: application/json

{
    "email": "vinhnguyenkhac20@gmail.com",
    "password": "123456"
}


### Update Password
POST https://do-an-da-nganh.onrender.com/api/users/updatePassword
Content-Type: application/json

{
    "email": "vinhnguyenkhac20@gmail.com",
    "password": "123456"
}


### Update information
POST https://do-an-da-nganh.onrender.com/api/users/updateInfo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aW5obmd1eWVua2hhYzIwQGdtYWlsLmNvbSIsImV4cCI6MTczMDkyMDg5OX0.KB4wCuIbWXzZRCnf1DZCMlM3f1sLvg49lnPN3AKBNWQ

{
    "first_name": "Nguyen",
    "last_name": "Vinh",
    "username": "johnnguyen",
    "email": "vinhnguyenkhac20@gmail.com",
    "phoneNumber": "0345",
    "address": "Road T, Block L"
}


### Refresh token
POST https://do-an-da-nganh.onrender.com/api/users/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aW5obmd1eWVua2hhYzIwQGdtYWlsLmNvbSIsImV4cCI6NDg1MDgwNjI2N30.LI2IzKX9gSCFYiadSUeHDXHG3KqiAOnTmlbDkkOtWUk


### Get all data Sensors
GET https://do-an-da-nganh.onrender.com/api/sensors/all/vinhnguyenkhac20@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aW5obmd1eWVua2hhYzIwQGdtYWlsLmNvbSIsImV4cCI6MTc0MDIxMzY0NH0.oJHAMZF-jQ6MrZRKQQcMGe1rIgA7uRpO4zn3ZAqrGpk

### Get all data Sensors month
GET https://do-an-da-nganh.onrender.com/api/sensors/all/month/vinhnguyenkhac20@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aW5obmd1eWVua2hhYzIwQGdtYWlsLmNvbSIsImV4cCI6MTc0MDIxMzY0NH0.oJHAMZF-jQ6MrZRKQQcMGe1rIgA7uRpO4zn3ZAqrGpk

### Get all data Sensors week
GET https://do-an-da-nganh.onrender.com/api/sensors/all/week/vinhnguyenkhac20@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aW5obmd1eWVua2hhYzIwQGdtYWlsLmNvbSIsImV4cCI6MTc0MDIxMzY0NH0.oJHAMZF-jQ6MrZRKQQcMGe1rIgA7uRpO4zn3ZAqrGpk

### Get all data Sensors day
GET https://do-an-da-nganh.onrender.com/api/sensors/all/day/vinhnguyenkhac20@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aW5obmd1eWVua2hhYzIwQGdtYWlsLmNvbSIsImV4cCI6MTc0MDIxMzY0NH0.oJHAMZF-jQ6MrZRKQQcMGe1rIgA7uRpO4zn3ZAqrGpk


### Update relay
POST https://do-an-da-nganh.onrender.com/api/relay/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aW5obmd1eWVua2hhYzIwQGdtYWlsLmNvbSIsImV4cCI6MTczNTk0MzEwMn0.axGSTNW0glHA-n6E3kXY_8lpJGgHxgSVGlg0eBv8ekQ

{
    "email_user": "vinhnguyen20@gmail.com",
    "relayName": "nutnhan-fan",
    "status": "ON"
}


### Create new relay
POST https://do-an-da-nganh.onrender.com/api/relay/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aW5obmd1eWVua2hhYzIwQGdtYWlsLmNvbSIsImV4cCI6MTczNTk0MzEwMn0.axGSTNW0glHA-n6E3kXY_8lpJGgHxgSVGlg0eBv8ekQ

{
    "email_user": "vinhnguyen@gmail.com",
    "relayName": "nutnhan-light",
    "status": "ON"
}




### Create new set up temperature
POST http://127.0.0.1:8080/api/setup/pir
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aW5obmd1eWVua2hhYzIwQGdtYWlsLmNvbSIsImV4cCI6MTczMTA5MDM2MX0.r8rgEL5GIP5ZIYi_sswaww1f9YaWcnZ1vf4HMVgUm48

{
    "email_user": "vinhnguyenkhac20@gmail.com",
    "pir_value": "1",
    "status": "ON"
}



### Create new set up pir
POST http://127.0.0.1:8080/api/setup/pir
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aW5obmd1eWVua2hhYzIwQGdtYWlsLmNvbSIsImV4cCI6MTczNDE1MDM3OX0.dWPYbRUA2JMUP8iWZJcn_W7nUAPWLU1Wx0YKsXWzZgU

{
    "email_user": "vinhnguyenkhac20@gmail.com",
    "pir_value": "0",
    "status": "OFF"
}



### Create new set up light
POST http://127.0.0.1:8080/api/setup/light
Content-Type: application/json


{
    "email_user": "vinhnguyenkhac20@gmail.com",
    "light_value": "80",
    "status": "OFF"
}

### Create new set up temperature
GET https://io.adafruit.com/api/v2/Vinhnguyen2003/feeds/sensors/data



### Create new set up temperature
POST http://127.0.0.1:8080/api/setup/temperature
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aW5obmd1eWVua2hhYzIwQGdtYWlsLmNvbSIsImV4cCI6MTczNDE1MDM3OX0.dWPYbRUA2JMUP8iWZJcn_W7nUAPWLU1Wx0YKsXWzZgU

{
    "email_user": "vinhnguyenkhac20@gmail.com",
    "temperature_value": "0",
    "status": "OFF"
}